### ISSUE TITLE
n64video.dll

### ISSUE THREAD

**Issue by brunotrevisan** [Nabile-Rahmani/DotN64#1] opened 2019-12-16 21:39 UTC
Not found dll

**Comment by Nabile-Rahmani** [comment] 2019-12-18 00:19
Did you first run the executable in its own empty folder ? The emulator detects missing dependencies for your system and downloads them automatically that way (I'll eventually more properly improve how it detects missing files). Just in case, do extract the folder in the archive before running the emulator.

Alternatively, you can manually run `DotN64.Desktop.exe --repair` to get what's necessary for it to run.

Do note that at this point it mostly runs test ROMs however.

I have some dormant uncommitted code that I need to tidy up, like a much-needed CPU pipeline rewrite, audio and video support and fixes, controller support, VI filter stuff, optimisations...

Even then, the most I can get out of it with commercial games is the boot screen of F-Zero X. Though the N64 OS looks to be working for test and custom ROMs.

For the homebrew part, the most impressive would be the [NICCC demo from PeterLemon](https://github.com/PeterLemon/N64/raw/master/N64NICCC/N64NICCC.N64), since it uses n64video.dll (Angrylion's video plugin) for graphics.

**Comment by Nabile-Rahmani** [comment] 2019-12-29 13:55
Closing this, as the updater/installer works as intended.

I did find a regression with Mono 6 on non-Windows platforms that I reported and is getting fixed. My code wasn't at fault.

Also, I pushed a preview release while I prepare the code for committing later on.

If you're curious, run `DotN64.Desktop.exe --update stream preview`, with [a bunch of nonsense ROMs here](https://french.waifu.download/Shared/N64.txt), and [test ROMs there](https://github.com/PeterLemon/N64).

**Closed as completed by Nabile-Rahmani** 2019-12-29 13:55 UTC
